version: '3.6'

services:
  node:
    build: 
      context: ./node
    image: node-beta
    container_name: node-compose
    volumes:
      - ./node:/app # feito para refletir todas as alteracoes no container
    networks:
      - nodenet
    ports:
      - "3000:3000"
  
  nginx:
    build: 
      context: ./nginx
    image: nginx-beta
    container_name: nginx-compose
    networks:
      - nodenet
    ports:
      - "8080:80"
    depends_on:
      - node
  
networks:
  nodenet:
    driver: bridge

